# Security Scan Composite Action
# Unified security scanning with multiple tools
#
# Usage:
#   - uses: gregorygreenspan/github-actions-library/composite-actions/security-scan@main
#     with:
#       scan-type: dependencies
#       fail-on: high

name: 'Security Scan'
description: 'Comprehensive security scanning for code, dependencies, and containers'
author: 'Gregory Greenspan'

branding:
  icon: 'shield'
  color: 'green'

inputs:
  scan-type:
    description: 'Type of scan (all/code/dependencies/secrets/container)'
    required: false
    default: 'all'
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  image:
    description: 'Container image to scan (for container scan type)'
    required: false
    default: ''
  fail-on:
    description: 'Severity threshold to fail (low/medium/high/critical)'
    required: false
    default: 'high'
  upload-sarif:
    description: 'Upload results to GitHub Security tab'
    required: false
    default: 'true'
  output-format:
    description: 'Output format (table/json/sarif)'
    required: false
    default: 'table'
  ignore-unfixed:
    description: 'Ignore vulnerabilities without fixes'
    required: false
    default: 'false'
  config-file:
    description: 'Path to scanner config file'
    required: false
    default: ''

outputs:
  vulnerabilities:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.summary.outputs.count }}
  critical:
    description: 'Number of critical vulnerabilities'
    value: ${{ steps.summary.outputs.critical }}
  high:
    description: 'Number of high vulnerabilities'
    value: ${{ steps.summary.outputs.high }}
  sarif-file:
    description: 'Path to SARIF output file'
    value: ${{ steps.trivy.outputs.sarif-file }}

runs:
  using: 'composite'
  steps:
    # Secret Detection
    - name: Secret Detection (Gitleaks)
      if: inputs.scan-type == 'all' || inputs.scan-type == 'secrets'
      shell: bash
      run: |
        echo "ðŸ” Scanning for secrets with Gitleaks..."
        curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.18.1/gitleaks_8.18.1_linux_x64.tar.gz | tar xz
        ./gitleaks detect --source="${{ inputs.path }}" --report-format=sarif --report-path=gitleaks.sarif --exit-code=0 || true
        if [ -f gitleaks.sarif ]; then
          echo "secrets_found=$(jq '.runs[0].results | length' gitleaks.sarif)" >> $GITHUB_OUTPUT
        fi

    # Code Scanning (SAST)
    - name: Setup Python for SAST
      if: (inputs.scan-type == 'all' || inputs.scan-type == 'code') && hashFiles('**/*.py') != ''
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: '3.11'

    - name: Run Bandit (Python SAST)
      if: (inputs.scan-type == 'all' || inputs.scan-type == 'code') && hashFiles('**/*.py') != ''
      shell: bash
      run: |
        pip install bandit
        bandit -r "${{ inputs.path }}" -f sarif -o bandit.sarif || true

    # Dependency Scanning
    - name: Run Trivy (Dependencies/Container)
      id: trivy
      if: inputs.scan-type != 'secrets' && inputs.scan-type != 'code'
      shell: bash
      run: |
        # Install Trivy
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.48.0
        
        SEVERITY="UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
        TRIVY_ARGS="--format sarif --output trivy-results.sarif --severity $SEVERITY"
        
        if [ "${{ inputs.ignore-unfixed }}" == "true" ]; then
          TRIVY_ARGS="$TRIVY_ARGS --ignore-unfixed"
        fi
        
        if [ -n "${{ inputs.config-file }}" ]; then
          TRIVY_ARGS="$TRIVY_ARGS --config ${{ inputs.config-file }}"
        fi
        
        if [ "${{ inputs.scan-type }}" == "container" ] && [ -n "${{ inputs.image }}" ]; then
          echo "ðŸ³ Scanning container image: ${{ inputs.image }}"
          trivy image $TRIVY_ARGS "${{ inputs.image }}"
        else
          echo "ðŸ“¦ Scanning filesystem: ${{ inputs.path }}"
          trivy fs $TRIVY_ARGS "${{ inputs.path }}"
        fi
        
        echo "sarif-file=trivy-results.sarif" >> $GITHUB_OUTPUT

    # Aggregate and summarize
    - name: Generate Summary
      id: summary
      shell: bash
      run: |
        echo "### ðŸ”’ Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        CRITICAL=0
        HIGH=0
        TOTAL=0
        
        if [ -f trivy-results.sarif ]; then
          CRITICAL=$(jq '[.runs[0].results[] | select(.level == "error")] | length' trivy-results.sarif 2>/dev/null || echo 0)
          HIGH=$(jq '[.runs[0].results[] | select(.level == "warning")] | length' trivy-results.sarif 2>/dev/null || echo 0)
          TOTAL=$(jq '.runs[0].results | length' trivy-results.sarif 2>/dev/null || echo 0)
        fi
        
        echo "| Severity | Count |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| ðŸ”´ Critical | $CRITICAL |" >> $GITHUB_STEP_SUMMARY
        echo "| ðŸŸ  High | $HIGH |" >> $GITHUB_STEP_SUMMARY
        echo "| ðŸ“Š Total | $TOTAL |" >> $GITHUB_STEP_SUMMARY
        
        echo "count=$TOTAL" >> $GITHUB_OUTPUT
        echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
        echo "high=$HIGH" >> $GITHUB_OUTPUT
        
        # Fail based on threshold
        FAIL_ON="${{ inputs.fail-on }}"
        case $FAIL_ON in
          critical)
            [ $CRITICAL -gt 0 ] && exit 1
            ;;
          high)
            [ $CRITICAL -gt 0 ] || [ $HIGH -gt 0 ] && exit 1
            ;;
        esac
        
        exit 0

    # Upload SARIF
    - name: Upload Trivy SARIF
      if: inputs.upload-sarif == 'true' && hashFiles('trivy-results.sarif') != ''
      uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2 # v3.24.0
      with:
        sarif_file: trivy-results.sarif
        category: 'security-scan'
