# Docker Build Composite Action
# A single action for building, tagging, and pushing Docker images
#
# Usage:
#   - uses: gregorygreenspan/github-actions-library/composite-actions/docker-build@main
#     with:
#       context: .
#       push: true
#       tags: myapp:latest

name: 'Docker Build'
description: 'Build and push multi-architecture Docker images with best practices'
author: 'Gregory Greenspan'

branding:
  icon: 'box'
  color: 'blue'

inputs:
  context:
    description: 'Docker build context'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  platforms:
    description: 'Target platforms (comma-separated)'
    required: false
    default: 'linux/amd64'
  push:
    description: 'Push image to registry'
    required: false
    default: 'false'
  load:
    description: 'Load image to local Docker daemon'
    required: false
    default: 'false'
  tags:
    description: 'Image tags (newline-separated)'
    required: true
  labels:
    description: 'Image labels (newline-separated KEY=VALUE)'
    required: false
    default: ''
  build-args:
    description: 'Build arguments (newline-separated KEY=VALUE)'
    required: false
    default: ''
  target:
    description: 'Target stage to build'
    required: false
    default: ''
  cache-from:
    description: 'Cache sources'
    required: false
    default: 'type=gha'
  cache-to:
    description: 'Cache destinations'
    required: false
    default: 'type=gha,mode=max'
  no-cache:
    description: 'Disable caching'
    required: false
    default: 'false'
  pull:
    description: 'Always pull base images'
    required: false
    default: 'false'
  sbom:
    description: 'Generate SBOM attestation'
    required: false
    default: 'true'
  provenance:
    description: 'Generate provenance attestation'
    required: false
    default: 'true'

outputs:
  image-id:
    description: 'Image ID'
    value: ${{ steps.build.outputs.imageid }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  metadata:
    description: 'Build metadata JSON'
    value: ${{ steps.build.outputs.metadata }}

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      if: contains(inputs.platforms, ',') || contains(inputs.platforms, 'arm')
      uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      with:
        platforms: ${{ inputs.platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      with:
        driver-opts: |
          image=moby/buildkit:v0.12.3

    - name: Build and push
      id: build
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        build-args: ${{ inputs.build-args }}
        target: ${{ inputs.target }}
        cache-from: ${{ inputs.no-cache == 'true' && '' || inputs.cache-from }}
        cache-to: ${{ inputs.no-cache == 'true' && '' || inputs.cache-to }}
        no-cache: ${{ inputs.no-cache }}
        pull: ${{ inputs.pull }}
        sbom: ${{ inputs.sbom }}
        provenance: ${{ inputs.provenance }}

    - name: Export digest
      if: inputs.push == 'true'
      shell: bash
      run: |
        echo "### Docker Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Image ID | \`${{ steps.build.outputs.imageid }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Digest | \`${{ steps.build.outputs.digest }}\` |" >> $GITHUB_STEP_SUMMARY
        echo "| Platforms | ${{ inputs.platforms }} |" >> $GITHUB_STEP_SUMMARY
