# Reusable Docker CI/CD Workflow
# Provides: Build, scan, test, and push multi-architecture container images
#
# Features:
# - Multi-arch builds (amd64/arm64) with QEMU
# - Layer caching for fast rebuilds
# - Vulnerability scanning with Trivy
# - SBOM generation
# - Image signing with cosign
# - Semantic versioning tags

name: Docker CI/CD

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of the Docker image (without registry prefix)'
        required: true
        type: string
      registry:
        description: 'Container registry URL'
        required: false
        type: string
        default: 'ghcr.io'
      context:
        description: 'Docker build context path'
        required: false
        type: string
        default: '.'
      dockerfile:
        description: 'Path to Dockerfile'
        required: false
        type: string
        default: 'Dockerfile'
      platforms:
        description: 'Target platforms for multi-arch build'
        required: false
        type: string
        default: 'linux/amd64,linux/arm64'
      push:
        description: 'Push image to registry'
        required: false
        type: boolean
        default: false
      scan-severity:
        description: 'Minimum severity to fail build (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
        required: false
        type: string
        default: 'HIGH,CRITICAL'
      build-args:
        description: 'Docker build arguments (multiline KEY=VALUE)'
        required: false
        type: string
        default: ''
      cache-from:
        description: 'Cache sources (type=gha,type=registry)'
        required: false
        type: string
        default: 'type=gha'
      cache-to:
        description: 'Cache destinations'
        required: false
        type: string
        default: 'type=gha,mode=max'
    secrets:
      registry-username:
        description: 'Registry username'
        required: false
      registry-password:
        description: 'Registry password/token'
        required: false
    outputs:
      image-digest:
        description: 'Image digest (sha256:...)'
        value: ${{ jobs.build.outputs.digest }}
      image-tags:
        description: 'Generated image tags'
        value: ${{ jobs.build.outputs.tags }}

# Minimal required permissions
permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
      tags: ${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
        with:
          platforms: ${{ inputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.3
            network=host

      - name: Log in to registry
        if: inputs.push
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry-username || github.actor }}
          password: ${{ secrets.registry-password || github.token }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}
          cache-from: ${{ inputs.cache-from }}
          cache-to: ${{ inputs.cache-to }}
          provenance: true
          sbom: true

      - name: Generate SBOM
        if: inputs.push
        uses: anchore/sbom-action@78fc58e266e87a38d4194b2137a3d4e9bcaf7ca1 # v0.15.0
        with:
          image: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}@${{ steps.build-push.outputs.digest }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM
        if: inputs.push
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: sbom
          path: sbom.spdx.json
          retention-days: 30

  scan:
    name: Security Scan
    needs: build
    runs-on: ubuntu-latest
    if: inputs.push
    
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@91713af97dc80187565512baba96e4364e983601 # v0.16.0
        with:
          image-ref: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}@${{ needs.build.outputs.digest }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ inputs.scan-severity }}
          vuln-type: 'os,library'
          scanners: 'vuln,secret,config'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2 # v3.24.0
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'container-security'

      - name: Fail on critical vulnerabilities
        uses: aquasecurity/trivy-action@91713af97dc80187565512baba96e4364e983601 # v0.16.0
        with:
          image-ref: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}@${{ needs.build.outputs.digest }}
          format: 'table'
          exit-code: '1'
          severity: ${{ inputs.scan-severity }}
          vuln-type: 'os,library'
